version: "3"

services:
  database:
    build: ./Database
    ports:
      - "5566:5432"

  backend:

    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/app.py:/var/opt/gis/app.py
  frontend:
    build: ./Frontend
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend/angular/src:/var/opt/angular/src
    

volumes:
  database-data:
