CREATE TABLE wahldaten21 (
id SERIAL,
Nr VARCHAR(254),
Gebiet VARCHAR(254),
gehört_zu VARCHAR(254),
Wahlberechtigte_1_eg VARCHAR(254),
Wahlberechtigte_1_vor VARCHAR(254),
Wahlberechtigte_2_eg VARCHAR(254),
Wahlberechtigte_2_vor VARCHAR(254),
Wählende_1_eg VARCHAR(254),
Wählende_1_vor VARCHAR(254),
Wählende_2_eg VARCHAR(254),
Wählende_2_vor VARCHAR(254),
Ungültige_Stimmen_1_eg VARCHAR(254),
Ungültige_Stimmen_1_vor VARCHAR(254),
Ungültige_Stimmen_2_eg VARCHAR(254),
Ungültige_Stimmen_2_vor VARCHAR(254),
Gültige_Stimmen_1_eg VARCHAR(254),
Gültige_Stimmen_1_vor VARCHAR(254),
Gültige_Stimmen_2_eg VARCHAR(254),
Gültige_Stimmen_2_vor VARCHAR(254),
Christlich_Demokratische_Union_Deutschlands_1_eg VARCHAR(254),
Christlich_Demokratische_Union_Deutschlands_1_vor VARCHAR(254),
Christlich_Demokratische_Union_Deutschlands_2_eg VARCHAR(254),
Christlich_Demokratische_Union_Deutschlands_2_vor VARCHAR(254),
Sozialdemokratische_Partei_Deutschlands_1_eg VARCHAR(254),
Sozialdemokratische_Partei_Deutschlands_1_vor VARCHAR(254),
Sozialdemokratische_Partei_Deutschlands_2_eg VARCHAR(254),
Sozialdemokratische_Partei_Deutschlands_2_vor VARCHAR(254),
Alternative_für_Deutschland_1_eg VARCHAR(254),
Alternative_für_Deutschland_1_vor VARCHAR(254),
Alternative_für_Deutschland_2_eg VARCHAR(254),
Alternative_für_Deutschland_2_vor VARCHAR(254),
Freie_Demokratische_Partei_1_eg VARCHAR(254),
Freie_Demokratische_Partei_1_vor VARCHAR(254),
Freie_Demokratische_Partei_2_eg VARCHAR(254),
Freie_Demokratische_Partei_2_vor VARCHAR(254),
DIE_LINKE_1_eg VARCHAR(254),
DIE_LINKE_1_vor VARCHAR(254),
DIE_LINKE_2_eg VARCHAR(254),
DIE_LINKE_2_vor VARCHAR(254),
BÜNDNIS_90DIE_GRÜNEN_1_eg VARCHAR(254),
BÜNDNIS_90DIE_GRÜNEN_1_vor VARCHAR(254),
BÜNDNIS_90DIE_GRÜNEN_2_eg VARCHAR(254),
BÜNDNIS_90DIE_GRÜNEN_2_vor VARCHAR(254),
ChristlichSoziale_Union_in_Bayern_eV_1_eg VARCHAR(254),
ChristlichSoziale_Union_in_Bayern_eV_1_vor VARCHAR(254),
ChristlichSoziale_Union_in_Bayern_eV_2_eg VARCHAR(254),
ChristlichSoziale_Union_in_Bayern_eV_2_vor VARCHAR(254),
FREIE_WÄHLER_1_eg VARCHAR(254),
FREIE_WÄHLER_1_vor VARCHAR(254),
FREIE_WÄHLER_2_eg VARCHAR(254),
FREIE_WÄHLER_2_vor VARCHAR(254),
Partei_für_Arbeit_Tierschutz_1_eg VARCHAR(254),
Partei_für_Arbeit_Tierschutz_1_vor VARCHAR(254),
Partei_für_Arbeit_Tierschutz_2_eg VARCHAR(254),
Partei_für_Arbeit_Tierschutz_2_vor VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_eg VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_vor VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_eg VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_vor VARCHAR(254),
Nationaldemokratische_Partei_Deutschlands_1_eg VARCHAR(254),
Nationaldemokratische_Partei_Deutschlands_1_vor VARCHAR(254),
Nationaldemokratische_Partei_Deutschlands_2_eg VARCHAR(254),
Nationaldemokratische_Partei_Deutschlands_2_vor VARCHAR(254),
Piratenpartei_Deutschland_1_eg VARCHAR(254),
Piratenpartei_Deutschland_1_vor VARCHAR(254),
Piratenpartei_Deutschland_2_eg VARCHAR(254),
Piratenpartei_Deutschland_2_vor VARCHAR(254),
ÖkologischDemokratische_Partei_1_eg VARCHAR(254),
ÖkologischDemokratische_Partei_1_vor VARCHAR(254),
ÖkologischDemokratische_Partei_2_eg VARCHAR(254),
ÖkologischDemokratische_Partei_2_vor VARCHAR(254),
VPartei3__Partei_für_Veränderung_1_eg VARCHAR(254),
VPartei3__Partei_für_Veränderung_1_vor VARCHAR(254),
VPartei3__Partei_für_Veränderung_2_eg VARCHAR(254),
VPartei3__Partei_für_Veränderung_2_vor VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_1_eg VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_1_vor VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_2_eg VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_2_vor VARCHAR(254),
Bayernpartei_1_eg VARCHAR(254),
Bayernpartei_1_vor VARCHAR(254),
Bayernpartei_2_eg VARCHAR(254),
Bayernpartei_2_vor VARCHAR(254),
Allianz_für_Menschenrechte_Tier_1_eg VARCHAR(254),
Allianz_für_Menschenrechte_Tier_1_vor VARCHAR(254),
Allianz_für_Menschenrechte_Tier_2_eg VARCHAR(254),
Allianz_für_Menschenrechte_Tier_2_vor VARCHAR(254),
MarxistischLeninistische_Partei_Deutschlands_1_eg VARCHAR(254),
MarxistischLeninistische_Partei_Deutschlands_1_vor VARCHAR(254),
MarxistischLeninistische_Partei_Deutschlands_2_eg VARCHAR(254),
MarxistischLeninistische_Partei_Deutschlands_2_vor VARCHAR(254),
Partei_für_Gesundheitsforschung_1_eg VARCHAR(254),
Partei_für_Gesundheitsforschung_1_vor VARCHAR(254),
Partei_für_Gesundheitsforschung_2_eg VARCHAR(254),
Partei_für_Gesundheitsforschung_2_vor VARCHAR(254),
Menschliche_Welt__für_das_Wohl_und_1_eg VARCHAR(254),
Menschliche_Welt__für_das_Wohl_und_1_vor VARCHAR(254),
Menschliche_Welt__für_das_Wohl_und_2_eg VARCHAR(254),
Menschliche_Welt__für_das_Wohl_und_2_vor VARCHAR(254),
Deutsche_Kommunistische_Partei_1_eg VARCHAR(254),
Deutsche_Kommunistische_Partei_1_vor VARCHAR(254),
Deutsche_Kommunistische_Partei_2_eg VARCHAR(254),
Deutsche_Kommunistische_Partei_2_vor VARCHAR(254),
Die_Grauen_–_Für_alle_Generationen_1_eg VARCHAR(254),
Die_Grauen_–_Für_alle_Generationen_1_vor VARCHAR(254),
Die_Grauen_–_Für_alle_Generationen_2_eg VARCHAR(254),
Die_Grauen_–_Für_alle_Generationen_2_vor VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_1_eg VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_1_vor VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_2_eg VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_2_vor VARCHAR(254),
Partei_der_Humanisten_1_eg VARCHAR(254),
Partei_der_Humanisten_1_vor VARCHAR(254),
Partei_der_Humanisten_2_eg VARCHAR(254),
Partei_der_Humanisten_2_vor VARCHAR(254),
Gartenpartei_1_eg VARCHAR(254),
Gartenpartei_1_vor VARCHAR(254),
Gartenpartei_2_eg VARCHAR(254),
Gartenpartei_2_vor VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_1_eg VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_1_vor VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_2_eg VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_2_vor VARCHAR(254),
Sozialistische_Gleichheitspartei_1_eg VARCHAR(254),
Sozialistische_Gleichheitspartei_1_vor VARCHAR(254),
Sozialistische_Gleichheitspartei_2_eg VARCHAR(254),
Sozialistische_Gleichheitspartei_2_vor VARCHAR(254),
Basisdemokratische_Partei_Deutschland_1_eg VARCHAR(254),
Basisdemokratische_Partei_Deutschland_1_vor VARCHAR(254),
Basisdemokratische_Partei_Deutschland_2_eg VARCHAR(254),
Basisdemokratische_Partei_Deutschland_2_vor VARCHAR(254),
Bündnis_C__Christen_für_Deutschland_1_eg VARCHAR(254),
Bündnis_C__Christen_für_Deutschland_1_vor VARCHAR(254),
Bündnis_C__Christen_für_Deutschland_2_eg VARCHAR(254),
Bündnis_C__Christen_für_Deutschland_2_vor VARCHAR(254),
Bürgerbewegung_für_Fortschritt_und_Wandel_1_eg VARCHAR(254),
Bürgerbewegung_für_Fortschritt_und_Wandel_1_vor VARCHAR(254),
Bürgerbewegung_für_Fortschritt_und_Wandel_2_eg VARCHAR(254),
Bürgerbewegung_für_Fortschritt_und_Wandel_2_vor VARCHAR(254),
DER_DRITTE_WEG_1_eg VARCHAR(254),
DER_DRITTE_WEG_1_vor VARCHAR(254),
DER_DRITTE_WEG_2_eg VARCHAR(254),
DER_DRITTE_WEG_2_vor VARCHAR(254),
diePinkenBÜNDNIS21_1_eg VARCHAR(254),
diePinkenBÜNDNIS21_1_vor VARCHAR(254),
diePinkenBÜNDNIS21_2_eg VARCHAR(254),
diePinkenBÜNDNIS21_2_vor VARCHAR(254),
Europäische_Partei_LIEBE_1_eg VARCHAR(254),
Europäische_Partei_LIEBE_1_vor VARCHAR(254),
Europäische_Partei_LIEBE_2_eg VARCHAR(254),
Europäische_Partei_LIEBE_2_vor VARCHAR(254),
LiberalKonservative_Reformer_1_eg VARCHAR(254),
LiberalKonservative_Reformer_1_vor VARCHAR(254),
LiberalKonservative_Reformer_2_eg VARCHAR(254),
LiberalKonservative_Reformer_2_vor VARCHAR(254),
Partei_des_Fortschritts_1_eg VARCHAR(254),
Partei_des_Fortschritts_1_vor VARCHAR(254),
Partei_des_Fortschritts_2_eg VARCHAR(254),
Partei_des_Fortschritts_2_vor VARCHAR(254),
_Partei_für_Kinder_Jugendliche_und_1_eg VARCHAR(254),
_Partei_für_Kinder_Jugendliche_und_1_vor VARCHAR(254),
_Partei_für_Kinder_Jugendliche_und_2_eg VARCHAR(254),
_Partei_für_Kinder_Jugendliche_und_2_vor VARCHAR(254),
Südschleswigscher_Wählerverband_1_eg VARCHAR(254),
Südschleswigscher_Wählerverband_1_vor VARCHAR(254),
Südschleswigscher_Wählerverband_2_eg VARCHAR(254),
Südschleswigscher_Wählerverband_2_vor VARCHAR(254),
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_1_eg VARCHAR(254),
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_1_vor VARCHAR(254),
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_2_eg VARCHAR(254),
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_2_vor VARCHAR(254),
UNABHÄNGIGE_für_bürgernahe_Demokratie_1_eg VARCHAR(254),
UNABHÄNGIGE_für_bürgernahe_Demokratie_1_vor VARCHAR(254),
UNABHÄNGIGE_für_bürgernahe_Demokratie_2_eg VARCHAR(254),
UNABHÄNGIGE_für_bürgernahe_Demokratie_2_vor VARCHAR(254),
Volt_Deutschland_1_eg VARCHAR(254),
Volt_Deutschland_1_vor VARCHAR(254),
Volt_Deutschland_2_eg VARCHAR(254),
Volt_Deutschland_2_vor VARCHAR(254),
Ab_jetztDemokratie_durch_Volksabstimmung_1_eg VARCHAR(254),
Ab_jetztDemokratie_durch_Volksabstimmung_1_vor VARCHAR(254),
Ab_jetztDemokratie_durch_Volksabstimmung_2_eg VARCHAR(254),
Ab_jetztDemokratie_durch_Volksabstimmung_2_vor VARCHAR(254),
bergpartei_die_überpartei_1_eg VARCHAR(254),
bergpartei_die_überpartei_1_vor VARCHAR(254),
bergpartei_die_überpartei_2_eg VARCHAR(254),
bergpartei_die_überpartei_2_vor VARCHAR(254),
DIE_SONSTIGEN__X_1_eg VARCHAR(254),
DIE_SONSTIGEN__X_1_vor VARCHAR(254),
DIE_SONSTIGEN__X_2_eg VARCHAR(254),
DIE_SONSTIGEN__X_2_vor VARCHAR(254),
FamilienPartei_Deutschlands_1_eg VARCHAR(254),
FamilienPartei_Deutschlands_1_vor VARCHAR(254),
FamilienPartei_Deutschlands_2_eg VARCHAR(254),
FamilienPartei_Deutschlands_2_vor VARCHAR(254),
Graue_Panther_1_eg VARCHAR(254),
Graue_Panther_1_vor VARCHAR(254),
Graue_Panther_2_eg VARCHAR(254),
Graue_Panther_2_vor VARCHAR(254),
Klimaliste_BadenWürttemberg_1_eg VARCHAR(254),
Klimaliste_BadenWürttemberg_1_vor VARCHAR(254),
Klimaliste_BadenWürttemberg_2_eg VARCHAR(254),
Klimaliste_BadenWürttemberg_2_vor VARCHAR(254),
Thüringer_Heimatpartei_1_eg VARCHAR(254),
Thüringer_Heimatpartei_1_vor VARCHAR(254),
Thüringer_Heimatpartei_2_eg VARCHAR(254),
Thüringer_Heimatpartei_2_vor VARCHAR(254),
Übrige_1_eg VARCHAR(254),
Übrige_1_vor VARCHAR(254),
Übrige_2_eg VARCHAR(254),
Übrige_2_vor VARCHAR(254),
  PRIMARY KEY (id)
);
COPY wahldaten21(
Nr,
Gebiet,
gehört_zu,
Wahlberechtigte_1_eg,
Wahlberechtigte_1_vor,
Wahlberechtigte_2_eg,
Wahlberechtigte_2_vor,
Wählende_1_eg,
Wählende_1_vor,
Wählende_2_eg,
Wählende_2_vor,
Ungültige_Stimmen_1_eg,
Ungültige_Stimmen_1_vor,
Ungültige_Stimmen_2_eg,
Ungültige_Stimmen_2_vor,
Gültige_Stimmen_1_eg,
Gültige_Stimmen_1_vor,
Gültige_Stimmen_2_eg,
Gültige_Stimmen_2_vor,
Christlich_Demokratische_Union_Deutschlands_1_eg,
Christlich_Demokratische_Union_Deutschlands_1_vor,
Christlich_Demokratische_Union_Deutschlands_2_eg,
Christlich_Demokratische_Union_Deutschlands_2_vor,
Sozialdemokratische_Partei_Deutschlands_1_eg,
Sozialdemokratische_Partei_Deutschlands_1_vor,
Sozialdemokratische_Partei_Deutschlands_2_eg,
Sozialdemokratische_Partei_Deutschlands_2_vor,
Alternative_für_Deutschland_1_eg,
Alternative_für_Deutschland_1_vor,
Alternative_für_Deutschland_2_eg,
Alternative_für_Deutschland_2_vor,
Freie_Demokratische_Partei_1_eg,
Freie_Demokratische_Partei_1_vor,
Freie_Demokratische_Partei_2_eg,
Freie_Demokratische_Partei_2_vor,
DIE_LINKE_1_eg,
DIE_LINKE_1_vor,
DIE_LINKE_2_eg,
DIE_LINKE_2_vor,
BÜNDNIS_90DIE_GRÜNEN_1_eg,
BÜNDNIS_90DIE_GRÜNEN_1_vor,
BÜNDNIS_90DIE_GRÜNEN_2_eg,
BÜNDNIS_90DIE_GRÜNEN_2_vor,
ChristlichSoziale_Union_in_Bayern_eV_1_eg,
ChristlichSoziale_Union_in_Bayern_eV_1_vor,
ChristlichSoziale_Union_in_Bayern_eV_2_eg,
ChristlichSoziale_Union_in_Bayern_eV_2_vor,
FREIE_WÄHLER_1_eg,
FREIE_WÄHLER_1_vor,
FREIE_WÄHLER_2_eg,
FREIE_WÄHLER_2_vor,
Partei_für_Arbeit_Tierschutz_1_eg,
Partei_für_Arbeit_Tierschutz_1_vor,
Partei_für_Arbeit_Tierschutz_2_eg,
Partei_für_Arbeit_Tierschutz_2_vor,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_eg,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_vor,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_eg,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_vor,
Nationaldemokratische_Partei_Deutschlands_1_eg,
Nationaldemokratische_Partei_Deutschlands_1_vor,
Nationaldemokratische_Partei_Deutschlands_2_eg,
Nationaldemokratische_Partei_Deutschlands_2_vor,
Piratenpartei_Deutschland_1_eg,
Piratenpartei_Deutschland_1_vor,
Piratenpartei_Deutschland_2_eg,
Piratenpartei_Deutschland_2_vor,
ÖkologischDemokratische_Partei_1_eg,
ÖkologischDemokratische_Partei_1_vor,
ÖkologischDemokratische_Partei_2_eg,
ÖkologischDemokratische_Partei_2_vor,
VPartei3__Partei_für_Veränderung_1_eg,
VPartei3__Partei_für_Veränderung_1_vor,
VPartei3__Partei_für_Veränderung_2_eg,
VPartei3__Partei_für_Veränderung_2_vor,
DEMOKRATIE_IN_BEWEGUNG_1_eg,
DEMOKRATIE_IN_BEWEGUNG_1_vor,
DEMOKRATIE_IN_BEWEGUNG_2_eg,
DEMOKRATIE_IN_BEWEGUNG_2_vor,
Bayernpartei_1_eg,
Bayernpartei_1_vor,
Bayernpartei_2_eg,
Bayernpartei_2_vor,
Allianz_für_Menschenrechte_Tier_1_eg,
Allianz_für_Menschenrechte_Tier_1_vor,
Allianz_für_Menschenrechte_Tier_2_eg,
Allianz_für_Menschenrechte_Tier_2_vor,
MarxistischLeninistische_Partei_Deutschlands_1_eg,
MarxistischLeninistische_Partei_Deutschlands_1_vor,
MarxistischLeninistische_Partei_Deutschlands_2_eg,
MarxistischLeninistische_Partei_Deutschlands_2_vor,
Partei_für_Gesundheitsforschung_1_eg,
Partei_für_Gesundheitsforschung_1_vor,
Partei_für_Gesundheitsforschung_2_eg,
Partei_für_Gesundheitsforschung_2_vor,
Menschliche_Welt__für_das_Wohl_und_1_eg,
Menschliche_Welt__für_das_Wohl_und_1_vor,
Menschliche_Welt__für_das_Wohl_und_2_eg,
Menschliche_Welt__für_das_Wohl_und_2_vor,
Deutsche_Kommunistische_Partei_1_eg,
Deutsche_Kommunistische_Partei_1_vor,
Deutsche_Kommunistische_Partei_2_eg,
Deutsche_Kommunistische_Partei_2_vor,
Die_Grauen_–_Für_alle_Generationen_1_eg,
Die_Grauen_–_Für_alle_Generationen_1_vor,
Die_Grauen_–_Für_alle_Generationen_2_eg,
Die_Grauen_–_Für_alle_Generationen_2_vor,
Bürgerrechtsbewegung_Solidarität_1_eg,
Bürgerrechtsbewegung_Solidarität_1_vor,
Bürgerrechtsbewegung_Solidarität_2_eg,
Bürgerrechtsbewegung_Solidarität_2_vor,
Partei_der_Humanisten_1_eg,
Partei_der_Humanisten_1_vor,
Partei_der_Humanisten_2_eg,
Partei_der_Humanisten_2_vor,
Gartenpartei_1_eg,
Gartenpartei_1_vor,
Gartenpartei_2_eg,
Gartenpartei_2_vor,
Die_Urbane_Eine_HipHop_Partei_1_eg,
Die_Urbane_Eine_HipHop_Partei_1_vor,
Die_Urbane_Eine_HipHop_Partei_2_eg,
Die_Urbane_Eine_HipHop_Partei_2_vor,
Sozialistische_Gleichheitspartei_1_eg,
Sozialistische_Gleichheitspartei_1_vor,
Sozialistische_Gleichheitspartei_2_eg,
Sozialistische_Gleichheitspartei_2_vor,
Basisdemokratische_Partei_Deutschland_1_eg,
Basisdemokratische_Partei_Deutschland_1_vor,
Basisdemokratische_Partei_Deutschland_2_eg,
Basisdemokratische_Partei_Deutschland_2_vor,
Bündnis_C__Christen_für_Deutschland_1_eg,
Bündnis_C__Christen_für_Deutschland_1_vor,
Bündnis_C__Christen_für_Deutschland_2_eg,
Bündnis_C__Christen_für_Deutschland_2_vor,
Bürgerbewegung_für_Fortschritt_und_Wandel_1_eg,
Bürgerbewegung_für_Fortschritt_und_Wandel_1_vor,
Bürgerbewegung_für_Fortschritt_und_Wandel_2_eg,
Bürgerbewegung_für_Fortschritt_und_Wandel_2_vor,
DER_DRITTE_WEG_1_eg,
DER_DRITTE_WEG_1_vor,
DER_DRITTE_WEG_2_eg,
DER_DRITTE_WEG_2_vor,
diePinkenBÜNDNIS21_1_eg,
diePinkenBÜNDNIS21_1_vor,
diePinkenBÜNDNIS21_2_eg,
diePinkenBÜNDNIS21_2_vor,
Europäische_Partei_LIEBE_1_eg,
Europäische_Partei_LIEBE_1_vor,
Europäische_Partei_LIEBE_2_eg,
Europäische_Partei_LIEBE_2_vor,
LiberalKonservative_Reformer_1_eg,
LiberalKonservative_Reformer_1_vor,
LiberalKonservative_Reformer_2_eg,
LiberalKonservative_Reformer_2_vor,
Partei_des_Fortschritts_1_eg,
Partei_des_Fortschritts_1_vor,
Partei_des_Fortschritts_2_eg,
Partei_des_Fortschritts_2_vor,
_Partei_für_Kinder_Jugendliche_und_1_eg,
_Partei_für_Kinder_Jugendliche_und_1_vor,
_Partei_für_Kinder_Jugendliche_und_2_eg,
_Partei_für_Kinder_Jugendliche_und_2_vor,
Südschleswigscher_Wählerverband_1_eg,
Südschleswigscher_Wählerverband_1_vor,
Südschleswigscher_Wählerverband_2_eg,
Südschleswigscher_Wählerverband_2_vor,
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_1_eg,
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_1_vor,
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_2_eg,
Team_Todenhöfer_–_Die_Gerechtigkeitspartei_2_vor,
UNABHÄNGIGE_für_bürgernahe_Demokratie_1_eg,
UNABHÄNGIGE_für_bürgernahe_Demokratie_1_vor,
UNABHÄNGIGE_für_bürgernahe_Demokratie_2_eg,
UNABHÄNGIGE_für_bürgernahe_Demokratie_2_vor,
Volt_Deutschland_1_eg,
Volt_Deutschland_1_vor,
Volt_Deutschland_2_eg,
Volt_Deutschland_2_vor,
Ab_jetztDemokratie_durch_Volksabstimmung_1_eg,
Ab_jetztDemokratie_durch_Volksabstimmung_1_vor,
Ab_jetztDemokratie_durch_Volksabstimmung_2_eg,
Ab_jetztDemokratie_durch_Volksabstimmung_2_vor,
bergpartei_die_überpartei_1_eg,
bergpartei_die_überpartei_1_vor,
bergpartei_die_überpartei_2_eg,
bergpartei_die_überpartei_2_vor,
DIE_SONSTIGEN__X_1_eg,
DIE_SONSTIGEN__X_1_vor,
DIE_SONSTIGEN__X_2_eg,
DIE_SONSTIGEN__X_2_vor,
FamilienPartei_Deutschlands_1_eg,
FamilienPartei_Deutschlands_1_vor,
FamilienPartei_Deutschlands_2_eg,
FamilienPartei_Deutschlands_2_vor,
Graue_Panther_1_eg,
Graue_Panther_1_vor,
Graue_Panther_2_eg,
Graue_Panther_2_vor,
Klimaliste_BadenWürttemberg_1_eg,
Klimaliste_BadenWürttemberg_1_vor,
Klimaliste_BadenWürttemberg_2_eg,
Klimaliste_BadenWürttemberg_2_vor,
Thüringer_Heimatpartei_1_eg,
Thüringer_Heimatpartei_1_vor,
Thüringer_Heimatpartei_2_eg,
Thüringer_Heimatpartei_2_vor,
Übrige_1_eg,
Übrige_1_vor,
Übrige_2_eg,
Übrige_2_vor)
FROM '/docker-entrypoint-initdb.d/wahl21.csv'
DELIMITER ';'
CSV HEADER;