CREATE TABLE wahldaten (
id SERIAL,
Nr VARCHAR(254),
Gebiet VARCHAR(254),
gehört_zu VARCHAR(254),
Wahlberechtigte_1_eg VARCHAR(254),
Wahlberechtigte_1_vor VARCHAR(254),
Wahlberechtigte_2_eg VARCHAR(254),
Wahlberechtigte_2_vor VARCHAR(254),
Wähler_1_eg VARCHAR(254),
Wähler_1_vor VARCHAR(254),
Wähler_2_eg VARCHAR(254),
Wähler_2_vor VARCHAR(254),
Ungültige_1_eg VARCHAR(254),
Ungültige_1_vor VARCHAR(254),
Ungültige_2_eg VARCHAR(254),
Ungültige_2_vor VARCHAR(254),
Gültige_1_eg VARCHAR(254),
Gültige_1_vor VARCHAR(254),
Gültige_2_eg VARCHAR(254),
Gültige_2_vor VARCHAR(254),
Christlich_Demokratische_Union_1_eg VARCHAR(254),
Christlich_Demokratische_Union_1_vor VARCHAR(254),
Christlich_Demokratische_Union_2_eg VARCHAR(254),
Christlich_Demokratische_Union_2_vor VARCHAR(254),
Sozialdemokratische_Partei_1_eg VARCHAR(254),
Sozialdemokratische_Partei_1_vor VARCHAR(254),
Sozialdemokratische_Partei_2_eg VARCHAR(254),
Sozialdemokratische_Partei_2_vor VARCHAR(254),
DIE_LINKE_1_eg VARCHAR(254),
DIE_LINKE_1_vor VARCHAR(254),
DIE_LINKE_2_eg VARCHAR(254),
DIE_LINKE_2_vor VARCHAR(254),
BÜNDNIS_90_DIE_GRÜNEN_1_eg VARCHAR(254),
BÜNDNIS_90_DIE_GRÜNEN_1_vor VARCHAR(254),
BÜNDNIS_90_DIE_GRÜNEN_2_eg VARCHAR(254),
BÜNDNIS_90_DIE_GRÜNEN_2_vor VARCHAR(254),
Christlich_Soziale_Union_1_eg VARCHAR(254),
Christlich_Soziale_Union_1_vor VARCHAR(254),
Christlich_Soziale_Union_2_eg VARCHAR(254),
Christlich_Soziale_Union_2_vor VARCHAR(254),
Freie_Demokratische_Partei_1_eg VARCHAR(254),
Freie_Demokratische_Partei_1_vor VARCHAR(254),
Freie_Demokratische_Partei_2_eg VARCHAR(254),
Freie_Demokratische_Partei_2_vor VARCHAR(254),
Alternative_für_Deutschland_1_eg VARCHAR(254),
Alternative_für_Deutschland_1_vor VARCHAR(254),
Alternative_für_Deutschland_2_eg VARCHAR(254),
Alternative_für_Deutschland_2_vor VARCHAR(254),
Piratenpartei_Deutschland_1_eg VARCHAR(254),
Piratenpartei_Deutschland_1_vor VARCHAR(254),
Piratenpartei_Deutschland_2_eg VARCHAR(254),
Piratenpartei_Deutschland_2_vor VARCHAR(254),
Nationaldemokratische_Partei_1_eg VARCHAR(254),
Nationaldemokratische_Partei_1_vor VARCHAR(254),
Nationaldemokratische_Partei_2_eg VARCHAR(254),
Nationaldemokratische_Partei_2_vor VARCHAR(254),
FREIE_WÄHLER_1_eg VARCHAR(254),
FREIE_WÄHLER_1_vor VARCHAR(254),
FREIE_WÄHLER_2_eg VARCHAR(254),
FREIE_WÄHLER_2_vor VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_eg VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_vor VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_eg VARCHAR(254),
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_vor VARCHAR(254),
Ökologisch_Demokratische_Partei_1_eg VARCHAR(254),
Ökologisch_Demokratische_Partei_1_vor VARCHAR(254),
Ökologisch_Demokratische_Partei_2_eg VARCHAR(254),
Ökologisch_Demokratische_Partei_2_vor VARCHAR(254),
PARTEI_1_eg VARCHAR(254),
PARTEI_1_vor VARCHAR(254),
PARTEI_2_eg VARCHAR(254),
PARTEI_2_vor VARCHAR(254),
Bayernpartei_1_eg VARCHAR(254),
Bayernpartei_1_vor VARCHAR(254),
Bayernpartei_2_eg VARCHAR(254),
Bayernpartei_2_vor VARCHAR(254),
Ab_jetzt_1_eg VARCHAR(254),
Ab_jetzt_1_vor VARCHAR(254),
Ab_jetzt_2_eg VARCHAR(254),
Ab_jetzt_2_vor VARCHAR(254),
Partei_der_Vernunft_1_eg VARCHAR(254),
Partei_der_Vernunft_1_vor VARCHAR(254),
Partei_der_Vernunft_2_eg VARCHAR(254),
Partei_der_Vernunft_2_vor VARCHAR(254),
Marxistisch_Leninistische_Partei_1_eg VARCHAR(254),
Marxistisch_Leninistische_Partei_1_vor VARCHAR(254),
Marxistisch_Leninistische_Partei_2_eg VARCHAR(254),
Marxistisch_Leninistische_Partei_2_vor VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_1_eg VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_1_vor VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_2_eg VARCHAR(254),
Bürgerrechtsbewegung_Solidarität_2_vor VARCHAR(254),
Sozialistische_Gleichheitspartei_1_eg VARCHAR(254),
Sozialistische_Gleichheitspartei_1_vor VARCHAR(254),
Sozialistische_Gleichheitspartei_2_eg VARCHAR(254),
Sozialistische_Gleichheitspartei_2_vor VARCHAR(254),
DIE_RECHTE_1_eg VARCHAR(254),
DIE_RECHTE_1_vor VARCHAR(254),
DIE_RECHTE_2_eg VARCHAR(254),
DIE_RECHTE_2_vor VARCHAR(254),
Allianz_Deutscher_Demokraten_1_eg VARCHAR(254),
Allianz_Deutscher_Demokraten_1_vor VARCHAR(254),
Allianz_Deutscher_Demokraten_2_eg VARCHAR(254),
Allianz_Deutscher_Demokraten_2_vor VARCHAR(254),
Allianz_für_Menschenrechte_1_eg VARCHAR(254),
Allianz_für_Menschenrechte_1_vor VARCHAR(254),
Allianz_für_Menschenrechte_2_eg VARCHAR(254),
Allianz_für_Menschenrechte_2_vor VARCHAR(254),
bergpartei_die_überpartei_1_eg VARCHAR(254),
bergpartei_die_überpartei_1_vor VARCHAR(254),
bergpartei_die_überpartei_2_eg VARCHAR(254),
bergpartei_die_überpartei_2_vor VARCHAR(254),
Bündnis_Grundeinkommen_1_eg VARCHAR(254),
Bündnis_Grundeinkommen_1_vor VARCHAR(254),
Bündnis_Grundeinkommen_2_eg VARCHAR(254),
Bündnis_Grundeinkommen_2_vor VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_1_eg VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_1_vor VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_2_eg VARCHAR(254),
DEMOKRATIE_IN_BEWEGUNG_2_vor VARCHAR(254),
Deutsche_Kommunistische_Partei_1_eg VARCHAR(254),
Deutsche_Kommunistische_Partei_1_vor VARCHAR(254),
Deutsche_Kommunistische_Partei_2_eg VARCHAR(254),
Deutsche_Kommunistische_Partei_2_vor VARCHAR(254),
Deutsche_Mitte_1_eg VARCHAR(254),
Deutsche_Mitte_1_vor VARCHAR(254),
Deutsche_Mitte_2_eg VARCHAR(254),
Deutsche_Mitte_2_vor VARCHAR(254),
Die_Grauen_1_eg VARCHAR(254),
Die_Grauen_1_vor VARCHAR(254),
Die_Grauen_2_eg VARCHAR(254),
Die_Grauen_2_vor VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_1_eg VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_1_vor VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_2_eg VARCHAR(254),
Die_Urbane_Eine_HipHop_Partei_2_vor VARCHAR(254),
Magdeburger_Gartenpartei_1_eg VARCHAR(254),
Magdeburger_Gartenpartei_1_vor VARCHAR(254),
Magdeburger_Gartenpartei_2_eg VARCHAR(254),
Magdeburger_Gartenpartei_2_vor VARCHAR(254),
Menschliche_Welt_1_eg VARCHAR(254),
Menschliche_Welt_1_vor VARCHAR(254),
Menschliche_Welt_2_eg VARCHAR(254),
Menschliche_Welt_2_vor VARCHAR(254),
Partei_der_Humanisten_1_eg VARCHAR(254),
Partei_der_Humanisten_1_vor VARCHAR(254),
Partei_der_Humanisten_2_eg VARCHAR(254),
Partei_der_Humanisten_2_vor VARCHAR(254),
Partei_für_Gesundheitsforschung_1_eg VARCHAR(254),
Partei_für_Gesundheitsforschung_1_vor VARCHAR(254),
Partei_für_Gesundheitsforschung_2_eg VARCHAR(254),
Partei_für_Gesundheitsforschung_2_vor VARCHAR(254),
Partei_für_Veränderung_Vegetarier_1_eg VARCHAR(254),
Partei_für_Veränderung_Vegetarier_1_vor VARCHAR(254),
Partei_für_Veränderung_Vegetarier_2_eg VARCHAR(254),
Partei_für_Veränderung_Vegetarier_2_vor VARCHAR(254),
Bündnis_C_1_eg VARCHAR(254),
Bündnis_C_1_vor VARCHAR(254),
Bündnis_C_2_eg VARCHAR(254),
Bündnis_C_2_vor VARCHAR(254),
DIE_EINHEIT_1_eg VARCHAR(254),
DIE_EINHEIT_1_vor VARCHAR(254),
DIE_EINHEIT_2_eg VARCHAR(254),
DIE_EINHEIT_2_vor VARCHAR(254),
Die_Violetten_1_eg VARCHAR(254),
Die_Violetten_1_vor VARCHAR(254),
Die_Violetten_2_eg VARCHAR(254),
Die_Violetten_2_vor VARCHAR(254),
Familien_Partei_1_eg VARCHAR(254),
Familien_Partei_1_vor VARCHAR(254),
Familien_Partei_2_eg VARCHAR(254),
Familien_Partei_2_vor VARCHAR(254),
Feministische_Partei_DIE_FRAUEN_1_eg VARCHAR(254),
Feministische_Partei_DIE_FRAUEN_1_vor VARCHAR(254),
Feministische_Partei_DIE_FRAUEN_2_eg VARCHAR(254),
Feministische_Partei_DIE_FRAUEN_2_vor VARCHAR(254),
Mieterpartei_1_eg VARCHAR(254),
Mieterpartei_1_vor VARCHAR(254),
Mieterpartei_2_eg VARCHAR(254),
Mieterpartei_2_vor VARCHAR(254),
Neue_Liberale_1_eg VARCHAR(254),
Neue_Liberale_1_vor VARCHAR(254),
Neue_Liberale_2_eg VARCHAR(254),
Neue_Liberale_2_vor VARCHAR(254),
UNABHÄNGIGE_1_eg VARCHAR(254),
UNABHÄNGIGE_1_vor VARCHAR(254),
UNABHÄNGIGE_2_eg VARCHAR(254),
UNABHÄNGIGE_2_vor VARCHAR(254),
Übrige_1_eg VARCHAR(254),
Übrige_1_vor VARCHAR(254),
Übrige_2_eg VARCHAR(254),
Übrige_2_vor VARCHAR(254),
  PRIMARY KEY (id)
);
COPY wahldaten(
Nr,
Gebiet,
gehört_zu,
Wahlberechtigte_1_eg,
Wahlberechtigte_1_vor,
Wahlberechtigte_2_eg,
Wahlberechtigte_2_vor,
Wähler_1_eg,
Wähler_1_vor,
Wähler_2_eg,
Wähler_2_vor,
Ungültige_1_eg,
Ungültige_1_vor,
Ungültige_2_eg,
Ungültige_2_vor,
Gültige_1_eg,
Gültige_1_vor,
Gültige_2_eg,
Gültige_2_vor,
Christlich_Demokratische_Union_1_eg,
Christlich_Demokratische_Union_1_vor,
Christlich_Demokratische_Union_2_eg,
Christlich_Demokratische_Union_2_vor,
Sozialdemokratische_Partei_1_eg,
Sozialdemokratische_Partei_1_vor,
Sozialdemokratische_Partei_2_eg,
Sozialdemokratische_Partei_2_vor,
DIE_LINKE_1_eg,
DIE_LINKE_1_vor,
DIE_LINKE_2_eg,
DIE_LINKE_2_vor,
BÜNDNIS_90_DIE_GRÜNEN_1_eg,
BÜNDNIS_90_DIE_GRÜNEN_1_vor,
BÜNDNIS_90_DIE_GRÜNEN_2_eg,
BÜNDNIS_90_DIE_GRÜNEN_2_vor,
Christlich_Soziale_Union_1_eg,
Christlich_Soziale_Union_1_vor,
Christlich_Soziale_Union_2_eg,
Christlich_Soziale_Union_2_vor,
Freie_Demokratische_Partei_1_eg,
Freie_Demokratische_Partei_1_vor,
Freie_Demokratische_Partei_2_eg,
Freie_Demokratische_Partei_2_vor,
Alternative_für_Deutschland_1_eg,
Alternative_für_Deutschland_1_vor,
Alternative_für_Deutschland_2_eg,
Alternative_für_Deutschland_2_vor,
Piratenpartei_Deutschland_1_eg,
Piratenpartei_Deutschland_1_vor,
Piratenpartei_Deutschland_2_eg,
Piratenpartei_Deutschland_2_vor,
Nationaldemokratische_Partei_1_eg,
Nationaldemokratische_Partei_1_vor,
Nationaldemokratische_Partei_2_eg,
Nationaldemokratische_Partei_2_vor,
FREIE_WÄHLER_1_eg,
FREIE_WÄHLER_1_vor,
FREIE_WÄHLER_2_eg,
FREIE_WÄHLER_2_vor,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_eg,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_1_vor,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_eg,
PARTEI_MENSCH_UMWELT_TIERSCHUTZ_2_vor,
Ökologisch_Demokratische_Partei_1_eg,
Ökologisch_Demokratische_Partei_1_vor,
Ökologisch_Demokratische_Partei_2_eg,
Ökologisch_Demokratische_Partei_2_vor,
PARTEI_1_eg,
PARTEI_1_vor,
PARTEI_2_eg,
PARTEI_2_vor,
Bayernpartei_1_eg,
Bayernpartei_1_vor,
Bayernpartei_2_eg,
Bayernpartei_2_vor,
Ab_jetzt_1_eg,
Ab_jetzt_1_vor,
Ab_jetzt_2_eg,
Ab_jetzt_2_vor,
Partei_der_Vernunft_1_eg,
Partei_der_Vernunft_1_vor,
Partei_der_Vernunft_2_eg,
Partei_der_Vernunft_2_vor,
Marxistisch_Leninistische_Partei_1_eg,
Marxistisch_Leninistische_Partei_1_vor,
Marxistisch_Leninistische_Partei_2_eg,
Marxistisch_Leninistische_Partei_2_vor,
Bürgerrechtsbewegung_Solidarität_1_eg,
Bürgerrechtsbewegung_Solidarität_1_vor,
Bürgerrechtsbewegung_Solidarität_2_eg,
Bürgerrechtsbewegung_Solidarität_2_vor,
Sozialistische_Gleichheitspartei_1_eg,
Sozialistische_Gleichheitspartei_1_vor,
Sozialistische_Gleichheitspartei_2_eg,
Sozialistische_Gleichheitspartei_2_vor,
DIE_RECHTE_1_eg,
DIE_RECHTE_1_vor,
DIE_RECHTE_2_eg,
DIE_RECHTE_2_vor,
Allianz_Deutscher_Demokraten_1_eg,
Allianz_Deutscher_Demokraten_1_vor,
Allianz_Deutscher_Demokraten_2_eg,
Allianz_Deutscher_Demokraten_2_vor,
Allianz_für_Menschenrechte_1_eg,
Allianz_für_Menschenrechte_1_vor,
Allianz_für_Menschenrechte_2_eg,
Allianz_für_Menschenrechte_2_vor,
bergpartei_die_überpartei_1_eg,
bergpartei_die_überpartei_1_vor,
bergpartei_die_überpartei_2_eg,
bergpartei_die_überpartei_2_vor,
Bündnis_Grundeinkommen_1_eg,
Bündnis_Grundeinkommen_1_vor,
Bündnis_Grundeinkommen_2_eg,
Bündnis_Grundeinkommen_2_vor,
DEMOKRATIE_IN_BEWEGUNG_1_eg,
DEMOKRATIE_IN_BEWEGUNG_1_vor,
DEMOKRATIE_IN_BEWEGUNG_2_eg,
DEMOKRATIE_IN_BEWEGUNG_2_vor,
Deutsche_Kommunistische_Partei_1_eg,
Deutsche_Kommunistische_Partei_1_vor,
Deutsche_Kommunistische_Partei_2_eg,
Deutsche_Kommunistische_Partei_2_vor,
Deutsche_Mitte_1_eg,
Deutsche_Mitte_1_vor,
Deutsche_Mitte_2_eg,
Deutsche_Mitte_2_vor,
Die_Grauen_1_eg,
Die_Grauen_1_vor,
Die_Grauen_2_eg,
Die_Grauen_2_vor,
Die_Urbane_Eine_HipHop_Partei_1_eg,
Die_Urbane_Eine_HipHop_Partei_1_vor,
Die_Urbane_Eine_HipHop_Partei_2_eg,
Die_Urbane_Eine_HipHop_Partei_2_vor,
Magdeburger_Gartenpartei_1_eg,
Magdeburger_Gartenpartei_1_vor,
Magdeburger_Gartenpartei_2_eg,
Magdeburger_Gartenpartei_2_vor,
Menschliche_Welt_1_eg,
Menschliche_Welt_1_vor,
Menschliche_Welt_2_eg,
Menschliche_Welt_2_vor,
Partei_der_Humanisten_1_eg,
Partei_der_Humanisten_1_vor,
Partei_der_Humanisten_2_eg,
Partei_der_Humanisten_2_vor,
Partei_für_Gesundheitsforschung_1_eg,
Partei_für_Gesundheitsforschung_1_vor,
Partei_für_Gesundheitsforschung_2_eg,
Partei_für_Gesundheitsforschung_2_vor,
Partei_für_Veränderung_Vegetarier_1_eg,
Partei_für_Veränderung_Vegetarier_1_vor,
Partei_für_Veränderung_Vegetarier_2_eg,
Partei_für_Veränderung_Vegetarier_2_vor,
Bündnis_C_1_eg,
Bündnis_C_1_vor,
Bündnis_C_2_eg,
Bündnis_C_2_vor,
DIE_EINHEIT_1_eg,
DIE_EINHEIT_1_vor,
DIE_EINHEIT_2_eg,
DIE_EINHEIT_2_vor,
Die_Violetten_1_eg,
Die_Violetten_1_vor,
Die_Violetten_2_eg,
Die_Violetten_2_vor,
Familien_Partei_1_eg,
Familien_Partei_1_vor,
Familien_Partei_2_eg,
Familien_Partei_2_vor,
Feministische_Partei_DIE_FRAUEN_1_eg,
Feministische_Partei_DIE_FRAUEN_1_vor,
Feministische_Partei_DIE_FRAUEN_2_eg,
Feministische_Partei_DIE_FRAUEN_2_vor,
Mieterpartei_1_eg,
Mieterpartei_1_vor,
Mieterpartei_2_eg,
Mieterpartei_2_vor,
Neue_Liberale_1_eg,
Neue_Liberale_1_vor,
Neue_Liberale_2_eg,
Neue_Liberale_2_vor,
UNABHÄNGIGE_1_eg,
UNABHÄNGIGE_1_vor,
UNABHÄNGIGE_2_eg,
UNABHÄNGIGE_2_vor,
Übrige_1_eg,
Übrige_1_vor,
Übrige_2_eg,
Übrige_2_vor)
FROM '/docker-entrypoint-initdb.d/wahl17.csv'
DELIMITER ';'
CSV HEADER;