CREATE TABLE strukturdaten (
  id SERIAL,
  land_name VARCHAR(254),
  wkr_nr VARCHAR(254),
  wkr_name VARCHAR(254),
  municipalities VARCHAR(254),
  area VARCHAR(254),
  pop VARCHAR(254),
  german_pop VARCHAR(254),
  foreigners VARCHAR(254),
  pop_density VARCHAR(254),
  pop_change_birth VARCHAR(254),
  pop_change_migration VARCHAR(254),
  age_18 VARCHAR(254),
  age_24 VARCHAR(254),
  age_34 VARCHAR(254),
  age_59 VARCHAR(254),
  age_74 VARCHAR(254),
  age_99 VARCHAR(254),
  area_built VARCHAR(254),
  area_nature VARCHAR(254),
  new_housing VARCHAR(254),
  existing_housing VARCHAR(254),
  living_area_per_home VARCHAR(254),
  living_area_per_person VARCHAR(254),
  cars VARCHAR(254),
  electric_cars VARCHAR(254),
  companies VARCHAR(254),
  companies_artisans VARCHAR(254),
  professional_school VARCHAR(254),
  school VARCHAR(254),
  primary_school VARCHAR(254),
  secondary_school VARCHAR(254),
  middle_school VARCHAR(254),
  high_school VARCHAR(254),
  day_care_3 VARCHAR(254),
  day_care_6 VARCHAR(254),
  income VARCHAR(254),
  gdp VARCHAR(254),
  employed VARCHAR(254),
  employed_primary VARCHAR(254),
  employed_secondary VARCHAR(254),
  employed_trades VARCHAR(254),
  employed_service VARCHAR(254),
  employed_other VARCHAR(254),
  sgb_2 VARCHAR(254),
  sgb_2_incapacitated VARCHAR(254),
  sgb_2_foreigners VARCHAR(254),
  unemployed VARCHAR(254),
  unemployed_men VARCHAR(254),
  unemployment_women VARCHAR(254),
  unemployment_15_24 VARCHAR(254),
  unemployment_55_64 VARCHAR(254),
  PRIMARY KEY (id)
);
COPY strukturdaten(
  land_name,
  wkr_nr,
  wkr_name,
  municipalities,
  area,
  pop,
  german_pop,
  foreigners,
  pop_density,
  pop_change_birth,
  pop_change_migration,
  age_18,
  age_24,
  age_34,
  age_59,
  age_74,
  age_99,
  area_built,
  area_nature,
  new_housing,
  existing_housing,
  living_area_per_home,
  living_area_per_person,
  cars,
  electric_cars,
  companies,
  companies_artisans,
  professional_school,
  school,
  primary_school,
  secondary_school,
  middle_school,
  high_school,
  day_care_3,
  day_care_6,
  income,
  gdp,
  employed,
  employed_primary,
  employed_secondary,
  employed_trades,
  employed_service,
  employed_other,
  sgb_2,
  sgb_2_incapacitated,
  sgb_2_foreigners,
  unemployed,
  unemployed_men,
  unemployment_women,
  unemployment_15_24,
  unemployment_55_64)
FROM '/docker-entrypoint-initdb.d/str.csv'
DELIMITER ';'
CSV HEADER;