CREATE TABLE wka (
id SERIAL,
ident VARCHAR(254),
gemeinde VARCHAR(254),
year VARCHAR(254),
wka VARCHAR(254),
c_wka VARCHAR(254),
ltw_grün VARCHAR(254),
ltw_afd VARCHAR(254),
ltw_wahlbet VARCHAR(254),
pop VARCHAR(254),
ant_aus VARCHAR(254),
ant_unemp VARCHAR(254),
ltw_cdu VARCHAR(254),
ltw_spd VARCHAR(254),
ltw_fdp VARCHAR(254),
ltw_linke VARCHAR(254),
ltw_other VARCHAR(254),
gemeindename VARCHAR(254),
state VARCHAR(254),
kreis VARCHAR(254),
osten VARCHAR(254),
btw_grün VARCHAR(254),
btw_afd VARCHAR(254),
btw_cdu VARCHAR(254),
btw_spd VARCHAR(254),
btw_fdp VARCHAR(254),
btw_linke VARCHAR(254),
btw_other VARCHAR(254),
wka_c VARCHAR(254),
ltw_q VARCHAR(254),
ln_grün VARCHAR(254),
ln_afd VARCHAR(254),
ln_cdu VARCHAR(254),
ln_spd VARCHAR(254),
ln_fdp VARCHAR(254),
ln_linke VARCHAR(254),
ln_other VARCHAR(254),
ln_pop VARCHAR(254),
pre_w VARCHAR(254),
id2 VARCHAR(254),
gr_gov VARCHAR(254),
urban1 VARCHAR(254),
vor2013 VARCHAR(254),
kreis_no VARCHAR(254),
av_age VARCHAR(254),
share_fem VARCHAR(254),
refugee VARCHAR(254),
academic VARCHAR(254),
avhouse VARCHAR(254),
  PRIMARY KEY (id)
);

COPY wka(
ident,
gemeinde,
year,
wka,
c_wka,
ltw_grün,
ltw_afd,
ltw_wahlbet,
pop,
ant_aus,
ant_unemp,
ltw_cdu,
ltw_spd,
ltw_fdp,
ltw_linke,
ltw_other,
gemeindename,
state,
kreis,
osten,
btw_grün,
btw_afd,
btw_cdu,
btw_spd,
btw_fdp,
btw_linke,
btw_other,
wka_c,
ltw_q,
ln_grün,
ln_afd,
ln_cdu,
ln_spd,
ln_fdp,
ln_linke,
ln_other,
ln_pop,
pre_w,
id2,
gr_gov,
urban1,
vor2013,
kreis_no,
av_age,
share_fem,
refugee,
academic,
avhouse)
FROM '/docker-entrypoint-initdb.d/wka.csv'
DELIMITER ','
CSV HEADER;